//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmericanBlackout.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicEvent
    {
        public MusicEvent()
        {
            this.Offers = new HashSet<Offer>();
            this.MusicGroups = new HashSet<MusicGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.TimeSpan> DoorTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Location { get; set; }
        public string AgeRange { get; set; }
        public string Image { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual ICollection<Offer> Offers { get; set; }
        public virtual ICollection<MusicGroup> MusicGroups { get; set; }

        public string ImageSmall
        {
            get
            {
                if (Image != null)
                    return string.Format("{0}{1}{2}",
                        Image.Substring(0, Image.LastIndexOf('.')), "s",
                        Image.Substring(Image.LastIndexOf('.'), Image.Length - Image.LastIndexOf('.')));

                return "";
            }
        }
    }
}
