//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmericanBlackout.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicRecording
    {
        public int Id { get; set; }
        public short Position { get; set; }
        public string Name { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public string ISRC { get; set; }
        public string Lyrics { get; set; }
        public Nullable<int> MusicAlbum { get; set; }
    
        public virtual MusicAlbum MusicAlbum1 { get; set; }
    }
}
