//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmericanBlackout.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Availability { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> VaildTo { get; set; }
        public Nullable<int> MusicEvent { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Product { get; set; }
    
        public virtual ItemAvailability ItemAvailability { get; set; }
        public virtual MusicEvent MusicEvent1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
