//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmericanBlackout.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationRole
    {
        public OrganizationRole()
        {
            this.MusicGroups = new HashSet<MusicGroup>();
            this.Roles = new HashSet<Role>();
            this.URLs = new HashSet<URL>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<MusicGroup> MusicGroups { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<URL> URLs { get; set; }
    }
}
