//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmericanBlackout.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.MusicEvents = new HashSet<MusicEvent>();
            this.MusicGroups = new HashSet<MusicGroup>();
            this.Place1 = new HashSet<Place>();
        }
    
        public int Id { get; set; }
        public string URL { get; set; }
        public string Name { get; set; }
        public Nullable<int> ContainedIn { get; set; }
        public Nullable<int> Address { get; set; }
        public string Type { get; set; }
    
        public virtual Address Address1 { get; set; }
        public virtual ICollection<MusicEvent> MusicEvents { get; set; }
        public virtual ICollection<MusicGroup> MusicGroups { get; set; }
        public virtual ICollection<Place> Place1 { get; set; }
        public virtual Place Place2 { get; set; }
    }
}
