//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmericanBlackout.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL
    {
        public URL()
        {
            this.MusicAlbums = new HashSet<MusicAlbum>();
            this.MusicGroups = new HashSet<MusicGroup>();
            this.OrganizationRoles = new HashSet<OrganizationRole>();
        }
    
        public int Id { get; set; }
        public string URI { get; set; }
    
        public virtual ICollection<MusicAlbum> MusicAlbums { get; set; }
        public virtual ICollection<MusicGroup> MusicGroups { get; set; }
        public virtual ICollection<OrganizationRole> OrganizationRoles { get; set; }
    }
}
