//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmericanBlackout.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoObject
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string Thumbnail { get; set; }
        public string URL { get; set; }
        public int MusicGroup { get; set; }
    
        public virtual MusicGroup MusicGroup1 { get; set; }
    }
}
